// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3XE2P4nIYMJv_0wcugv-CkbdM3Orc6JM',
    appId: '1:608849931488:web:1edf9496e616581e93b485',
    messagingSenderId: '608849931488',
    projectId: 'test-eb10a',
    authDomain: 'test-eb10a.firebaseapp.com',
    storageBucket: 'test-eb10a.firebasestorage.app',
    measurementId: 'G-5PH8D2H6FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzHaBdfIXEtakOSo9d2_WlpNwRGgT4APk',
    appId: '1:608849931488:android:ad001b68620af1b893b485',
    messagingSenderId: '608849931488',
    projectId: 'test-eb10a',
    storageBucket: 'test-eb10a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASCJqaxT9OnXiIvG9ZKHvhwY6KO3FnBu0',
    appId: '1:608849931488:ios:87f21269cae0aa4f93b485',
    messagingSenderId: '608849931488',
    projectId: 'test-eb10a',
    storageBucket: 'test-eb10a.firebasestorage.app',
    iosBundleId: 'com.smartqueue.user.smartqueueUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASCJqaxT9OnXiIvG9ZKHvhwY6KO3FnBu0',
    appId: '1:608849931488:ios:87f21269cae0aa4f93b485',
    messagingSenderId: '608849931488',
    projectId: 'test-eb10a',
    storageBucket: 'test-eb10a.firebasestorage.app',
    iosBundleId: 'com.smartqueue.user.smartqueueUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3XE2P4nIYMJv_0wcugv-CkbdM3Orc6JM',
    appId: '1:608849931488:web:5b6d00909df82b9493b485',
    messagingSenderId: '608849931488',
    projectId: 'test-eb10a',
    authDomain: 'test-eb10a.firebaseapp.com',
    storageBucket: 'test-eb10a.firebasestorage.app',
    measurementId: 'G-X167JJQET1',
  );
}
